pimcore:
    documents:
        doc_types:
            definitions:
                4062ca67-74eb-4617-b93b-160059da06a1:
                    name: 'Teaser Snippet'
                    group: null
                    controller: 'ToolboxBundle\Controller\SnippetController::teaserAction'
                    template: null
                    type: snippet
                    priority: 0
                    creationDate: 1645459342
                    modificationDate: 1645459343
                    staticGeneratorEnabled: null
